### PR TITLE
Feature/emg 1583 assembly metadata

### PR DESCRIPTION
**Pull request by mberacochea**

### CODE REVIEW

**Comment by gustavo-salazar** [comment]
Code seems OK. 
Maybe add or edit a test for `/runs/XXX/assemblies`, that checks that `coverage` and `min_gap_length` are been serialized  and `study` is excluded

**Comment by mberacochea** [comment]
> Code seems OK.
> Maybe add or edit a test for `/runs/XXX/assemblies`, that checks that `coverage` and `min_gap_length` are been serialized and `study` is excluded

I agree, I will add a couple of unit tests.

**Review by caballero — APPROVED** [review]
chnages are ok

**Review by Vkale1 — APPROVED** [review]

**Comment by mberacochea** [comment]
> Code seems OK.
> Maybe add or edit a test for `/runs/XXX/assemblies`, that checks that `coverage` and `min_gap_length` are been serialized and `study` is excluded

I've added 2 unit tests for import_assembly and the new fields.

**Review by gustavo-salazar — APPROVED** [review]

**Pull request merged**
